// examples/solid-app/server.ts
import { serve } from "aleph/server";
import SolidLoader from "aleph/solid-loader";
import { generateHydrationScript, renderToString } from "solid-js/web";
import routes from "./routes/_export.ts";

serve({
  baseUrl: import.meta.url,
  loaders: [new SolidLoader()],
  router: { routes },
  ssr: (ctx) => {
    const App = ctx.routeModules[0].defaultExport; // routes/index.tsx
    ctx.headCollection.push(generateHydrationScript());
    return renderToString(App);
  },
});

// examples/feature-apps/suspense-ssr/server.tsx
import { App } from "aleph/react";
import { serve } from "aleph/server";
import { renderToReadableStream } from "react-dom/server";

serve({
  baseUrl: import.meta.url,
  routes: "./routes/**/*.tsx",
  ssr: {
    dataDefer: true,
    render: (ctx) => renderToReadableStream(<App ssrContext={ctx} />, ctx),
  },
});
