// examples/solid-app/server.ts
import { serve } from "aleph/server";
import SolidLoader from "aleph/solid-loader";
import { generateHydrationScript, renderToString } from "solid-js/web";
import routes from "./routes/_export.ts";

serve({
  baseUrl: import.meta.url,
  loaders: [new SolidLoader()],
  router: { routes },
  ssr: (ctx) => {
    const App = ctx.routeModules[0].defaultExport; // routes/index.tsx
    ctx.headCollection.push(generateHydrationScript());
    return renderToString(App);
  },
});

// examples/feature-apps/unocss/server.tsx
import presetUno from "@unocss/preset-uno.ts";
import presetIcons from "@unocss/preset-icons.ts";
import { App } from "aleph/react";
import { serve } from "aleph/server";
import { renderToString } from "react-dom/server";

serve({
  baseUrl: import.meta.url,
  routes: "./routes/**/*.tsx",
  unocss: {
    presets: [
      presetUno(),
      presetIcons({
        cdn: "https://esm.sh/",
      }),
    ],
  },
  ssr: (ctx) => renderToString(<App ssrContext={ctx} />),
});
