// runtime/react/server.ts
import { createElement } from "react";
import { renderToReadableStream } from "react-dom/server";
import { serve as alephServe, type ServerOptions } from "../../server/mod.ts";
import type { SSRContext, SSROptions } from "../../server/types.ts";
import { App } from "./router.ts";

if (Deno.args.includes("--dev")) {
  // Enable react refresh
  Deno.env.set("REACT_REFRESH", "true");
}

const render = (ctx: SSRContext) => {
  return renderToReadableStream(createElement(App, { ssrContext: ctx }), ctx);
};

export function serve(
  options?: Omit<ServerOptions, "ssr"> & { ssr?: boolean | (SSROptions & { suspense?: boolean }) },
) {
  alephServe({
    ...options,
    ssr: options?.ssr
      ? {
        ...(typeof options.ssr === "object" ? options.ssr : {}),
        render,
      }
      : undefined,
  });
}

// framework/solid/server.ts
import { createComponent } from "solid-js";
import { generateHydrationScript, renderToStream } from "solid-js/web";
import { serve as alephServe, type ServeOptions } from "../../server/mod.ts";
import type { SSRContext, SSROptions } from "../../server/types.ts";
import SolidTransformer from "./transformer.ts";

const render = (ctx: SSRContext): ReadableStream | string => {
  const App = ctx.modules[0]?.exports.default; // routes/index.tsx
  if (!App) {
    ctx.setStatus(404);
    return "<p>404 page not found</p>";
  }
  ctx.headCollection.push(generateHydrationScript());
  const { readable, writable } = new TransformStream();
  renderToStream(
    () => createComponent(App as () => null, {}),
    { nonce: ctx.nonce },
  ).pipeTo(writable);
  return readable;
};

export function serve(options?: Omit<ServeOptions, "ssr"> & { ssr?: boolean | SSROptions }) {
  alephServe({
    ...options,
    loaders: [...(options?.loaders ?? []), new SolidTransformer()],
    ssr: options?.ssr
      ? {
        ...(typeof options.ssr === "object" ? options.ssr : {}),
        render,
      }
      : undefined,
  });
}
